baseURL: "https://spandigital.github.io/sem-serv-docs"
languageCode: "en-us"
title: "Semantic Service Naming"
copyright: SPAN Digital Inc.
description: "Create meaningful service names that are unlikely to change over time and don’t replicate data in existing identifiers by composing the name from three elements that describe what the service does"
enableGitInfo: false
pluralizelisttitles: false
markup:
  goldmark:
    renderer:
      Unsafe: true
    parser:
      attribute:
        block: true
  highlight:
    style: github
menu:
  main:
    - identifier: versions
      name: versions
      url: /
      weight: 1
outputFormats:
  MenuIndex:
    baseName: menu
    mediaType: application/json
  SearchMap:
    baseName: searchmap
    mediaType: application/json
outputs:
  home:
    - HTML
    - RSS
    - MenuIndex
    - SearchMap
  page:
    - HTML
    - Embed
  section:
    - HTML
    - Embed
module:
  imports:
    - path: github.com/spandigital/presidium-layouts-base
    - path: github.com/spandigital/presidium-styling-base
params:
  appleScope: ''
  audience: ''
  basePath: "/"
  enterprise_key: sem-serv-docs
  site_prefix: ""
  frontmatter:
  - key: author
    strict: true
    type: email
  - key: title
    strict: true
    type: text
  lazyLoad: false
  logo: /images/logo.svg
  scope: ''
  show:
    author: false
    role: false
    status: false
  sortByFilePath: false
enableInlineShortcodes: true
frontmatter:
  lastmod:
    - lastmod
    - :fileModTime
    - :default
